"""
Dynamic Mini SIEM API - Fully Real-Time Event-Driven System
Continuously generates events, processes them, and broadcasts alerts
"""

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from datetime import datetime
from typing import Dict, Any
import asyncio
import logging

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Import services
from backend.event_generator import event_generator
from backend.alert_service import alert_service
from backend.api.websocket_manager import manager
from backend.database.mongo import alerts_collection, db
from backend.security.ip_blocker import get_blocked_ips

# ============================================
# FASTAPI APP INITIALIZATION
# ============================================

app = FastAPI(
    title="Mini SIEM - Dynamic Real-Time Security Monitoring",
    description="AI-powered real-time security monitoring with continuous event generation",
    version="2.1.0"
)

# CORS Configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:3001", "*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================
# GLOBAL STATE
# ============================================

event_generation_task = None


# ============================================
# EVENT PROCESSING CALLBACK
# ============================================

async def process_generated_event(event: Dict[str, Any]):
    """Callback to process events generated by event generator"""
    try:
        # Process event through alert service
        alert = await alert_service.process_event(event)
        
        # Broadcast updated statistics
        await broadcast_statistics()
        
    except Exception as e:
        logger.error(f"Error processing generated event: {e}")


async def broadcast_statistics():
    """Calculate and broadcast current statistics"""
    try:
        # Get statistics from MongoDB
        total = alerts_collection.count_documents({})
        high = alerts_collection.count_documents({"severity": "HIGH"})
        medium = alerts_collection.count_documents({"severity": "MEDIUM"})
        low = alerts_collection.count_documents({"severity": "LOW"})
        
        # Get threat distribution
        pipeline = [
            {"$group": {"_id": "$threat_type", "count": {"$sum": 1}}},
            {"$sort": {"count": -1}},
            {"$limit": 10}
        ]
        threat_distribution = list(alerts_collection.aggregate(pipeline))
        
        # Get blocked IPs count
        blocked_ips_count = len(get_blocked_ips())
        
        stats = {
            "total_alerts": total,
            "by_severity": {
                "HIGH": high,
                "MEDIUM": medium,
                "LOW": low
            },
            "threat_distribution": threat_distribution,
            "blocked_ips": blocked_ips_count,
            "active_connections": manager.get_connection_count(),
            "timestamp": datetime.utcnow().isoformat()
        }
        
        await manager.broadcast_statistics(stats)
        
    except Exception as e:
        logger.error(f"Error broadcasting statistics: {e}")


# ============================================
# STARTUP & SHUTDOWN EVENTS
# ============================================

@app.on_event("startup")
async def startup_event():
    """Start background tasks on application startup"""
    global event_generation_task
    
    logger.info("🚀 Starting Mini SIEM Dynamic System...")
    
    # Start WebSocket heartbeat
    manager.start_heartbeat()
    
    # Start event generator
    event_generation_task = asyncio.create_task(
        event_generator.start(process_generated_event)
    )
    
    logger.info("✅ Mini SIEM is now LIVE and generating events!")


@app.on_event("shutdown")
async def shutdown_event():
    """Cleanup on application shutdown"""
    logger.info("🛑 Shutting down Mini SIEM...")
    
    # Stop event generator
    event_generator.stop()
    
    if event_generation_task:
        event_generation_task.cancel()
    
    logger.info("✅ Mini SIEM shutdown complete")


# ============================================
# ROOT ENDPOINT
# ============================================

@app.get("/")
def home():
    return {
        "message": "Mini SIEM v2.1 - Dynamic Real-Time Security Monitoring",
        "status": "operational",
        "mode": "live_event_generation",
        "features": [
            "Continuous event generation",
            "Real-time ML detection",
            "WebSocket live updates",
            "Automated IP blocking",
            "Email notifications",
            "Dynamic risk scoring"
        ]
    }


# ============================================
# WEBSOCKET ENDPOINT
# ============================================

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """WebSocket endpoint for real-time alert streaming"""
    
    await manager.connect(websocket)
    
    # Send initial statistics
    await broadcast_statistics()
    
    try:
        while True:
            # Keep connection alive and receive messages
            data = await websocket.receive_text()
            
            # Echo back for heartbeat
            await websocket.send_json({
                "type": "pong",
                "message": "connected",
                "timestamp": datetime.utcnow().isoformat()
            })
    
    except WebSocketDisconnect:
        manager.disconnect(websocket)
    except Exception as e:
        logger.error(f"WebSocket error: {e}")
        manager.disconnect(websocket)


# ============================================
# ALERT ENDPOINTS
# ============================================

@app.get("/alerts")
async def get_all_alerts(limit: int = 100):
    """Get all alerts with optional limit"""
    
    alerts = alerts_collection.find().sort("timestamp", -1).limit(limit)
    
    result = []
    for alert in alerts:
        alert["_id"] = str(alert["_id"])
        result.append(alert)
    
    return result


@app.get("/alerts/severity/{severity}")
async def get_alerts_by_severity(severity: str):
    """Get alerts filtered by severity"""
    
    alerts = alerts_collection.find({"severity": severity.upper()}).sort("timestamp", -1)
    
    result = []
    for alert in alerts:
        alert["_id"] = str(alert["_id"])
        result.append(alert)
    
    return result


@app.get("/alerts/stats")
async def get_alert_statistics():
    """Get alert statistics"""
    
    total = alerts_collection.count_documents({})
    high = alerts_collection.count_documents({"severity": "HIGH"})
    medium = alerts_collection.count_documents({"severity": "MEDIUM"})
    low = alerts_collection.count_documents({"severity": "LOW"})
    
    # Get threat type distribution
    pipeline = [
        {"$group": {"_id": "$threat_type", "count": {"$sum": 1}}},
        {"$sort": {"count": -1}}
    ]
    threat_distribution = list(alerts_collection.aggregate(pipeline))
    
    # Get recent alerts timeline (last hour)
    from datetime import timedelta
    one_hour_ago = datetime.utcnow() - timedelta(hours=1)
    recent_alerts = alerts_collection.count_documents({
        "timestamp": {"$gte": one_hour_ago}
    })
    
    return {
        "total_alerts": total,
        "by_severity": {
            "HIGH": high,
            "MEDIUM": medium,
            "LOW": low
        },
        "threat_distribution": threat_distribution,
        "recent_alerts_last_hour": recent_alerts
    }


@app.get("/alerts/timeline")
async def get_alerts_timeline(minutes: int = 60):
    """Get alerts timeline for last N minutes"""
    
    from datetime import timedelta
    
    time_ago = datetime.utcnow() - timedelta(minutes=minutes)
    
    pipeline = [
        {"$match": {"timestamp": {"$gte": time_ago}}},
        {"$group": {
            "_id": {
                "$dateToString": {
                    "format": "%Y-%m-%d %H:%M",
                    "date": "$timestamp"
                }
            },
            "count": {"$sum": 1}
        }},
        {"$sort": {"_id": 1}}
    ]
    
    timeline = list(alerts_collection.aggregate(pipeline))
    
    return {
        "timeline": timeline,
        "period_minutes": minutes
    }


# ============================================
# SECURITY MANAGEMENT ENDPOINTS
# ============================================

@app.get("/security/blocked-ips")
async def get_blocked_ip_list():
    """Get list of all blocked IPs"""
    return get_blocked_ips()


@app.post("/security/block-ip")
async def block_ip_address(ip_address: str, reason: str = "Manual block"):
    """Manually block an IP address"""
    
    from backend.security.ip_blocker import block_ip
    
    block_ip(ip_address, reason)
    
    # Broadcast block notification
    await manager.broadcast_ip_block(ip_address, reason)
    
    return {"message": f"IP {ip_address} blocked successfully", "ip_address": ip_address}


@app.post("/security/unblock-ip")
async def unblock_ip_address(ip_address: str):
    """Unblock an IP address"""
    
    from backend.security.ip_blocker import unblock_ip
    
    unblock_ip(ip_address)
    
    return {"message": f"IP {ip_address} unblocked successfully", "ip_address": ip_address}


# ============================================
# SYSTEM STATUS
# ============================================

@app.get("/system/status")
async def get_system_status():
    """Get overall system status"""
    
    total_alerts = alerts_collection.count_documents({})
    high_alerts = alerts_collection.count_documents({"severity": "HIGH"})
    blocked_ips_count = len(get_blocked_ips())
    
    status = {
        "status": "operational",
        "mode": "live_event_generation",
        "total_alerts": total_alerts,
        "high_severity_alerts": high_alerts,
        "blocked_ips": blocked_ips_count,
        "active_websocket_connections": manager.get_connection_count(),
        "event_generator_running": event_generator.running,
        "timestamp": datetime.utcnow().isoformat()
    }
    
    return status


@app.get("/system/health")
async def health_check():
    """Health check endpoint"""
    
    try:
        # Test MongoDB connection
        db.command('ping')
        db_status = "connected"
    except:
        db_status = "disconnected"
    
    return {
        "status": "healthy",
        "database": db_status,
        "event_generator": "running" if event_generator.running else "stopped",
        "websocket_connections": manager.get_connection_count(),
        "timestamp": datetime.utcnow().isoformat()
    }


# ============================================
# CONTROL ENDPOINTS (FOR TESTING)
# ============================================

@app.post("/control/start-events")
async def start_event_generation():
    """Manually start event generation (if stopped)"""
    global event_generation_task
    
    if not event_generator.running:
        event_generation_task = asyncio.create_task(
            event_generator.start(process_generated_event)
        )
        return {"message": "Event generation started", "status": "running"}
    else:
        return {"message": "Event generation already running", "status": "running"}


@app.post("/control/stop-events")
async def stop_event_generation():
    """Manually stop event generation (for testing)"""
    
    event_generator.stop()
    
    if event_generation_task:
        event_generation_task.cancel()
    
    return {"message": "Event generation stopped", "status": "stopped"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
